name: Fetch Telegram Messages

on:
  push:
    branches:
      - main

jobs:
  fetch-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Fetch messages
        run: |
          python -c "
          import os
          from telegram import Bot

          bot = Bot(token='5978875502:AAFHqLOAQahaMklBX7n9K3GUk7YCKIm2sF0')
          updates = bot.get_updates(limit=50, channel_post='@CloudCityy')

          with open('messages.txt', 'w') as f:
              for update in updates:
                  f.write(update.message.text)
                  f.write('\n-------------\n')
          "

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add messages.txt
          git commit -m "Add messages.txt"
          git push
