name: Fetch Telegram Messages

on:
  push:
    branches:
      - main

jobs:
  fetch-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon

      - name: Fetch messages
        run: |
          python -c "
          from telethon.sync import TelegramClient

          api_id = '26963557'
          api_hash = '70aed19a29d2321933d9c4f652534c0f'
          bot_token = '5978875502:AAFHqLOAQahaMklBX7n9K3GUk7YCKIm2sF0'

          with TelegramClient(bot_token, api_id, api_hash) as client:
              for message in client.iter_messages('YOUR_CHANNEL_ID', limit=50):
                  with open('messages.txt', 'a') as f:
                      f.write(message.text)
                      f.write('\n-------------\n')
          "

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add messages.txt
          git commit -m "Add messages.txt"
          git push
