name: Telegram VLess Link Fetcher

on: 
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon

    - name: Run script
      run: |
        python -c "
        from telethon.sync import TelegramClient
        from telethon.tl.functions.messages import GetHistoryRequest
        import re

        api_id = '26963557'
        api_hash = '70aed19a29d2321933d9c4f652534c0f'
        session = 'anon.session'
        channel_username = '@V2rayCollectorDonate'

        client = TelegramClient(session, api_id, api_hash)

        async def main():
            async with client:
                channel_entity = await client.get_entity(channel_username)
                posts = await client(GetHistoryRequest(
                    peer=channel_entity,
                    limit=20,
                    offset_date=None,
                    offset_id=0,
                    max_id=0,
                    min_id=0,
                    add_offset=0,
                    hash=0))

                vless_links = []
                for message in posts.messages:
                    links = re.findall('vless://[^\s]+', message.message)
                    vless_links.extend(links)

                with open(f'{channel_username}.txt', 'w') as f:
                    for link in vless_links:
                        f.write(f'{link}\n')

        client.loop.run_until_complete(main())
        "

    - name: Commit and push
      run: |
        git config --local user.email "Your GitHub email"
        git config --local user.name "Your GitHub username"
        git add -A
        git commit -m "Add vless links"
        git push
