name: Telegram VLess Link Fetcher

on: 
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install aiogram
        pip install logging
        pip install asyncio
        
    - name: Run script
      run: python Scripts/Music.py

    - name: Commit and push
      run: |
        git config --local user.email "Your GitHub email"
        git config --local user.name "Your GitHub username"
        git add -A
        git commit -m "Add vless links"
        git push
